### ISSUE TITLE
Module doesn't start anymore with module not found (3.1.0)

### ISSUE THREAD

**Issue by mrwiwi** [fmartinou/tydom2mqtt#100]
Hello there, glad to see my original project still alive, sorry for not being active, work and all...

Critical error since this morning :

3.1 : can't start : 

Traceback (most recent call last):
  File "/app/main.py", line 8, in <module>
    from configuration.Configuration import Configuration
  File "/app/configuration/Configuration.py", line 7, in <module>
    from tydom.TydomClient import TydomClient
  File "/app/tydom/TydomClient.py", line 12, in <module>
    from const import *
ModuleNotFoundError: No module named 'const'

using old local config.

(so for quick message, on mobile)

**Comment by paulva** [comment]
Hello,
I have exactly the same issue. Also after updating to 3.10.
I hope you can fix it. Thanks!
Paul

**Comment by fmartinou** [comment]
Hi,

Sorry for the bug; a fix is on the go.

**Comment by fmartinou** [comment]
Mark as resolved.

(remaining errors are track on #101)

**Comment by paulva** [comment]
Hi, since today there was no communication with the devices anymore, restarted everything but no luck.

All entities say: "This entity is no longer being provided by the mqtt integration. If the entity is no longer in use, delete it in settings."

Startup log for tydom2mqtt is below.

I hope you can help,

Best regards,

Paul


2023-08-31 16:51:26,100 - Starting tydom2mqtt
2023-08-31 16:51:26,102 - Hassio environment detected: loading configuration from /data/options.json
2023-08-31 16:51:28,545 - Validating configuration ({
    "deltadore_login": "tydom@hooloovoo.nl",
    "deltadore_password": "T*******!",
    "log_level": "INFO",
    "mqtt_host": "homeassistant",
    "mqtt_password": "H*******!",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "mqtt",
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "1****6",
    "tydom_ip": "tydom-060656.local.",
    "tydom_mac": "001A25060656",
    "tydom_password": "5*************b"
}
2023-08-31 16:51:28,546 - The configuration is valid
2023-08-31 16:51:28,547 - tydom.TydomClient    - INFO    - Configure local mode (tydom-060656.local.)
2023-08-31 16:51:28,557 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=homeassistant, port=1883, user=mqtt, ssl=False)
2023-08-31 16:51:28,579 - tydom.TydomClient    - INFO    - Connecting to tydom
2023-08-31 16:51:33,393 - mqtt.MqttClient      - INFO    - Connected to mqtt broker
2023-08-31 16:51:33,906 - tydom.TydomClient    - INFO    - Connected to tydom
2023-08-31 16:51:33,907 - tydom.TydomClient    - INFO    - Setup tydom client
2023-08-31 16:51:34,253 - tydom.MessageHandler - INFO    - Device update (id=1677931239, endpoint=1677931239, name=Kantoor, type=boiler)
2023-08-31 16:51:34,258 - tydom.MessageHandler - INFO    - Device update (id=1677934327, endpoint=1677934327, name=James, type=boiler)
2023-08-31 16:51:34,263 - tydom.MessageHandler - INFO    - Device update (id=1677934401, endpoint=1677934401, name=Ties, type=boiler)
2023-08-31 16:51:34,268 - tydom.MessageHandler - INFO    - Device update (id=1677935731, endpoint=1677935731, name=Badkamer beneden, type=boiler)
2023-08-31 16:51:34,275 - tydom.MessageHandler - INFO    - Device update (id=1677935900, endpoint=1677935900, name=Badkamer boven, type=boiler)
2023-08-31 16:51:34,282 - tydom.MessageHandler - INFO    - Device update (id=1677949107, endpoint=1677949107, name=Chemëne, type=boiler)
2023-08-31 16:51:34,288 - tydom.MessageHandler - INFO    - Device update (id=1677959594, endpoint=1677959594, name=Woonkamer noord, type=boiler)
2023-08-31 16:51:34,293 - tydom.MessageHandler - INFO    - Device update (id=1677959780, endpoint=1677959780, name=Woonkamer zuid, type=boiler)
2023-08-31 16:51:34,304 - tydom.MessageHandler - INFO    - Device update (id=1677995637, endpoint=1677995637, name=Keuken zuid, type=boiler)
2023-08-31 16:51:34,312 - tydom.MessageHandler - INFO    - Device update (id=1677995714, endpoint=1677995714, name=Keuken noord, type=boiler)
2023-08-31 16:51:34,319 - tydom.MessageHandler - INFO    - Device update (id=1677998923, endpoint=1677998923, name=Serre zuid, type=boiler)
2023-08-31 16:51:34,323 - tydom.MessageHandler - INFO    - Device update (id=1677998987, endpoint=1677998987, name=Serre noord, type=boiler)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 125, in <module>
    main()
  File "/app/main.py", line 121, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 55, in listen_tydom
    await message_handler.incoming_triage()
  File "/app/tydom/MessageHandler.py", line 309, in incoming_triage
    await self.parse_response(incoming)
  File "/app/tydom/MessageHandler.py", line 346, in parse_response
    logger.warning('Unknown message type received', data)
Message: 'Unknown message type received'
Arguments: ('[]\r\n',)
