### ISSUE TITLE
Exception dans le fichier MessageHandler.py

### ISSUE THREAD

**Issue by phil2fer** [fmartinou/tydom2mqtt#122]
Bonjour et bravo pour ce projet qui me permet d'interfacer  facilement ma box Tydom avec OpenHab

j'ai  une exception qui se lève ligne 346 dans le fichier MessageHandler.py

`--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 125, in <module>
    main()
  File "/app/main.py", line 121, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 55, in listen_tydom
    await message_handler.incoming_triage()
  File "/app/tydom/MessageHandler.py", line 309, in incoming_triage
    await self.parse_response(incoming)
  File "/app/tydom/MessageHandler.py", line 346, in parse_response
    logger.warning('Unknown message type received', data)
Message: 'Unknown message type received'
Arguments: ('[]\r\n',)`

Est ce que vous pouvez corriger la ligne 346 
`logger.warning('Unknown message type received', data)`
en la remplaçant par
 `logger.warning('Unknown message type received %s', data)`

Merci

**Comment by am11r** [comment]
Bonjour,
J'ai la meme erreur. Tout se passe bien au debut: connexion, detection des "sensors" et puis immediatemnt apres ce meme log.
est ce une erreur de ma part quelque part?
en vous remerciant

**Comment by am11r** [comment]
Hi,
Always logs error after the last update…

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 125, in <module>
    main()
  File "/app/main.py", line 121, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 55, in listen_tydom
    await message_handler.incoming_triage()
  File "/app/tydom/MessageHandler.py", line 309, in incoming_triage
    await self.parse_response(incoming)
  File "/app/tydom/MessageHandler.py", line 346, in parse_response
    logger.warning('Unknown message type received', data)
Message: 'Unknown message type received'
Arguments: ('[]\r\n',)

any idea?

thanks for help

**Comment by fmartinou** [comment]
Merci pour avoir remonté l'erreur ; j'ai corrigé.
Ca sera dispo dans la prochaine version.

**Comment by fmartinou** [comment]
Released as `3.4.1`
