### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shadorlo** [fmartinou/tydom2mqtt#148]
`2023-10-25 20:34:04,420 - Starting tydom2mqtt
2023-10-25 20:34:04,422 - Hassio environment detected: loading configuration from /data/options.json
2023-10-25 20:34:04,427 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "ERROR",
    "mqtt_host": "homeassistant",
    "mqtt_password": "u************0",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "user132456789",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "mediation.tydom.com",
    "tydom_mac": "001A25020082",
    "tydom_password": "C******1"
}
2023-10-25 20:34:04,428 - The configuration is valid
2023-10-25 20:34:06,363 - tydom.MessageHandler - ERROR   - Error on parsing tydom response ('NoneType' object has no attribute 'publish')
2023-10-25 20:34:06,364 - tydom.MessageHandler - ERROR   - Incoming data ([{"id":1645988476,"endpoints":[{"id":1645988476,"error":0,"data":[{"name":"authorization","validity":"upToDate","value":"STOP"},{"name":"setpoint","validity":"upToDate","value":null},{"name":"thermicLevel","validity":"upToDate","value":"STOP"},{"name":"hvacMode","validity":"upToDate","value":"NORMAL"},{"name":"timeDelay","validity":"upToDate","value":0},{"name":"temperature","validity":"upToDate","value":20.200},{"name":"tempoOn","validity":"upToDate","value":false},{"name":"antifrostOn","validity":"upToDate","value":false},{"name":"loadSheddingOn","validity":"upToDate","value":false},{"name":"openingDetected","validity":"upToDate","value":false},{"name":"presenceDetected","validity":"upToDate","value":false},{"name":"absence","validity":"upToDate","value":false},{"name":"productionDefect","validity":"upToDate","value":false},{"name":"batteryCmdDefect","validity":"upToDate","value":false},{"name":"tempSensorDefect","validity":"upToDate","value":false},{"name":"tempSensorShortCut","validity":"upToDate","value":false},{"name":"tempSensorOpenCirc","validity":"upToDate","value":false},{"name":"boostOn","validity":"upToDate","value":false},{"name":"anticipCoeff","validity":"upToDate","value":30}]}]},{"id":1652815136,"endpoints":[{"id":1652815136,"error":15,"data":[{"name":"thermicDefect","validity":"expired","value":false}]}]},{"id":1698147441,"endpoints":[{"id":1698147441,"error":0,"data":[{"name":"alarmState","validity":"upToDate","value":"OFF"},{"name":"alarmMode","validity":"upToDate","value":"OFF"},{"name":"alarmTechnical","validity":"upToDate","value":false},{"name":"alarmSOS","validity":"upToDate","value":false},{"name":"unitAutoProtect","validity":"upToDate","value":false},{"name":"unitBatteryDefect","validity":"upToDate","value":false},{"name":"unackedEvent","validity":"upToDate","value":true},{"name":"systAutoProtect","validity":"upToDate","value":false},{"name":"systBatteryDefect","validity":"upToDate","value":true},{"name":"systSupervisionDefect","validity":"upToDate","value":false},{"name":"systOpenIssue","validity":"upToDate","value":false},{"name":"systSectorDefect","validity":"upToDate","value":false},{"name":"systTechnicalDefect","validity":"upToDate","value":false},{"name":"videoLinkDefect","validity":"upToDate","value":false},{"name":"remoteSurveyDefect","validity":"upToDate","value":false},{"name":"simDefect","validity":"upToDate","value":false},{"name":"networkDefect","validity":"upToDate","value":true},{"name":"inactiveProduct","validity":"upToDate","value":false},{"name":"liveCheckRunning","validity":"upToDate","value":false},{"name":"zone1State","validity":"upToDate","value":"UNUSED"},{"name":"zone2State","validity":"upToDate","value":"UNUSED"},{"name":"zone3State","validity":"upToDate","value":"UNUSED"},{"name":"zone4State","validity":"upToDate","value":"UNUSED"},{"name":"zone5State","validity":"upToDate","value":"UNUSED"},{"name":"zone6State","validity":"upToDate","value":"UNUSED"},{"name":"zone7State","validity":"upToDate","value":"UNUSED"},{"name":"zone8State","validity":"upToDate","value":"UNUSED"},{"name":"outTemperature","validity":"upToDate","value":null},{"name":"gsmLevel","validity":"upToDate","value":7},{"name":"irv1State","validity":"upToDate","value":"AVAILABLE"},{"name":"irv2State","validity":"upToDate","value":"UNAVAILABLE"},{"name":"irv3State","validity":"upToDate","value":"UNAVAILABLE"},{"name":"irv4State","validity":"upToDate","value":"UNAVAILABLE"},{"name":"kernelUpToDate","validity":"upToDate","value":true},{"name":"preAlarm","validity":"expired","value":false}]}]}]
)
2023-10-25 20:34:06,366 - tydom.MessageHandler - ERROR   - 'NoneType' object has no attribute 'publish'
Traceback (most recent call last):
  File "/app/tydom/MessageHandler.py", line 360, in parse_response
    await self.parse_devices_data(parsed=parsed)
  File "/app/tydom/MessageHandler.py", line 470, in parse_devices_data
    await self.parse_endpoint_data(endpoint, i["id"])
  File "/app/tydom/MessageHandler.py", line 707, in parse_endpoint_data
    await new_sh_hvac.update()
  File "/app/sensors/Boiler.py", line 114, in update
    await self.setup()
  File "/app/sensors/Boiler.py", line 109, in setup
    self.mqtt.mqtt_client.publish(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish'`

Bonjour,
Connaisez-vous cette erreur ?
Bonne soirée

**Comment by BlacKTM1190** [comment]
Hello
Après une lecture en diagonale, j'imagine que tu as un Tydom2 et un hvac.
Pour nous aider à t'aider, peux-tu préciser les références de tes modeles de Tydom et surtout d'hvac ?

**Comment by Shadorlo** [comment]
C'est un Tydom 1.0 et tydom2 et c'est quoi hvac ?

Je possède le Pack alarme 8 zones sans fil connecté avec transmetteur GSM et détecteur de levée de doute vidéo
je possède un récepteur pour chauffage lequel je me ne souviens plus
Pareil pour le portail je possède un apapreil de chez Delta dore ou j'ai plus sa référence

**Comment by BlacKTM1190** [comment]
> je possède un récepteur pour chauffage lequel je me ne souviens plus

C'est celui-ci, le hvac, qui provoque l'erreur.
Certains utilisateurs (ce qui n'est pas mon cas) pilotent leur chauffage avec Tydom2MQTT.
Des PR ont dernièrement été validés, comme le #118 pour la compatibilité des modèles ou le #124 pour les modes.
Utilises-tu la dernière release ? Arrives-tu à piloter le chauffage depuis l'app Tydom ?
