### ISSUE TITLE
Tydom

### ISSUE THREAD

**Issue by Shadorlo** [fmartinou/tydom2mqtt#167]
`/app/tydom/TydomClient.py:312: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is "ACK":
2024-01-06 16:24:06,838 - Starting tydom2mqtt
2024-01-06 16:24:06,840 - Hassio environment detected: loading configuration from /data/options.json
2024-01-06 16:24:06,845 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "INFO",
    "mqtt_host": "homeassistant",
    "mqtt_password": "p*************9",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "user123456798",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "mediation.tydom.com",
    "tydom_mac": "001A25020082",
    "tydom_password": "C******1"
}
2024-01-06 16:24:06,846 - The configuration is valid
2024-01-06 16:24:06,848 - tydom.TydomClient    - INFO    - Configure remote mode (mediation.tydom.com)
2024-01-06 16:24:06,912 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=homeassistant, port=1883, user=user123456798, ssl=False)
2024-01-06 16:24:06,962 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-01-06 16:24:07,422 - tydom.TydomClient    - INFO    - Connected to tydom
2024-01-06 16:24:07,423 - tydom.TydomClient    - INFO    - Setup tydom client
2024-01-06 16:24:07,732 - tydom.MessageHandler - INFO    - Device update (id=1645988476, endpoint=1645988476, name=Chauffage 1, type=boiler)
2024-01-06 16:24:07,733 - tydom.MessageHandler - ERROR   - Error on parsing tydom response ('NoneType' object has no attribute 'publish')
2024-01-06 16:24:07,737 - tydom.MessageHandler - ERROR   - Incoming data ([{"id":1645988476,"endpoints":[{"id":1645988476,"error":0,"data":[{"name":"authorization","validity":"upToDate","value":"HEATING"},{"name":"setpoint","validity":"upToDate","value":20.000},{"name":"thermicLevel","validity":"upToDate","value":null},{"name":"hvacMode","validity":"upToDate","value":"NORMAL"},{"name":"timeDelay","validity":"upToDate","value":0},{"name":"temperature","validity":"upToDate","value":20.590},{"name":"tempoOn","validity":"upToDate","value":false},{"name":"antifrostOn","validity":"upToDate","value":false},{"name":"loadSheddingOn","validity":"upToDate","value":false},{"name":"openingDetected","validity":"upToDate","value":false},{"name":"presenceDetected","validity":"upToDate","value":false},{"name":"absence","validity":"upToDate","value":false},{"name":"productionDefect","validity":"upToDate","value":false},{"name":"batteryCmdDefect","validity":"upToDate","value":false},{"name":"tempSensorDefect","validity":"upToDate","value":false},{"name":"tempSensorShortCut","validity":"upToDate","value":false},{"name":"tempSensorOpenCirc","validity":"upToDate","value":false},{"name":"boostOn","validity":"upToDate","value":false},{"name":"anticipCoeff","validity":"upToDate","value":30}]}]},{"id":1652815136,"endpoints":[{"id":1652815136,"error":15,"data":[{"name":"thermicDefect","validity":"expired","value":false}]}]},{"id":1698147441,"endpoints":[{"id":1698147441,"error":0,"data":[{"name":"alarmState","validity":"upToDate","value":"OFF"},{"name":"alarmMode","validity":"upToDate","value":"OFF"},{"name":"alarmTechnical","validity":"upToDate","value":false},{"name":"alarmSOS","validity":"upToDate","value":false},{"name":"unitAutoProtect","validity":"upToDate","value":false},{"name":"unitBatteryDefect","validity":"upToDate","value":false},{"name":"unackedEvent","validity":"upToDate","value":true},{"name":"systAutoProtect","validity":"upToDate","value":false},{"name":"systBatteryDefect","validity":"upToDate","value":true},{"name":"systSupervisionDefect","validity":"upToDate","value":false},{"name":"systOpenIssue","validity":"upToDate","value":false},{"name":"systSectorDefect","validity":"upToDate","value":false},{"name":"systTechnicalDefect","validity":"upToDate","value":false},{"name":"videoLinkDefect","validity":"upToDate","value":false},{"name":"remoteSurveyDefect","validity":"upToDate","value":false},{"name":"simDefect","validity":"upToDate","value":false},{"name":"networkDefect","validity":"upToDate","value":true},{"name":"inactiveProduct","validity":"upToDate","value":false},{"name":"liveCheckRunning","validity":"upToDate","value":false},{"name":"zone1State","validity":"upToDate","value":"UNUSED"},{"name":"zone2State","validity":"upToDate","value":"UNUSED"},{"name":"zone3State","validity":"upToDate","value":"UNUSED"},{"name":"zone4State","validity":"upToDate","value":"UNUSED"},{"name":"zone5State","validity":"upToDate","value":"UNUSED"},{"name":"zone6State","validity":"upToDate","value":"UNUSED"},{"name":"zone7State","validity":"upToDate","value":"UNUSED"},{"name":"zone8State","validity":"upToDate","value":"UNUSED"},{"name":"outTemperature","validity":"upToDate","value":null},{"name":"gsmLevel","validity":"upToDate","value":7},{"name":"irv1State","validity":"upToDate","value":"AVAILABLE"},{"name":"irv2State","validity":"upToDate","value":"UNAVAILABLE"},{"name":"irv3State","validity":"upToDate","value":"UNAVAILABLE"},{"name":"irv4State","validity":"upToDate","value":"UNAVAILABLE"},{"name":"kernelUpToDate","validity":"upToDate","value":true},{"name":"preAlarm","validity":"expired","value":false}]}]}]
)
2024-01-06 16:24:07,742 - tydom.MessageHandler - ERROR   - 'NoneType' object has no attribute 'publish'
Traceback (most recent call last):
  File "/app/tydom/MessageHandler.py", line 362, in parse_response
    await self.parse_devices_data(parsed=parsed)
  File "/app/tydom/MessageHandler.py", line 472, in parse_devices_data
    await self.parse_endpoint_data(endpoint, i["id"])
  File "/app/tydom/MessageHandler.py", line 709, in parse_endpoint_data
    await new_sh_hvac.update()
  File "/app/sensors/Boiler.py", line 115, in update
    await self.setup()
  File "/app/sensors/Boiler.py", line 110, in setup
    self.mqtt.mqtt_client.publish(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish'
2024-01-06 16:24:07,774 - tydom.MessageHandler - WARNING - Unknown message type received ([]

)
2024-01-06 16:24:09,504 - mqtt.MqttClient      - INFO    - Connected to mqtt broker
2024-01-06 16:25:07,738 - __main__             - ERROR   - Websocket connection closed: received 1000 (OK); then sent 1000 (OK)
2024-01-06 16:25:07,739 - tydom.TydomClient    - INFO    - Disconnecting
2024-01-06 16:25:07,741 - tydom.TydomClient    - INFO    - Disconnected
2024-01-06 16:25:07,742 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-01-06 16:25:07,970 - tydom.TydomClient    - INFO    - Connected to tydom
2024-01-06 16:25:07,972 - tydom.TydomClient    - INFO    - Setup tydom client
2024-01-06 16:25:08,253 - tydom.MessageHandler - INFO    - Device update (id=1645988476, endpoint=1645988476, name=Chauffage 1, type=boiler)
2024-01-06 16:25:08,271 - tydom.MessageHandler - INFO    - Device update (id=1698147441, endpoint=1698147441, name=Tyxal Alarm, type=alarm)
2024-01-06 16:25:08,277 - sensors.Sensor       - INFO    - Binary sensor created / updated : alarmState OFF
2024-01-06 16:25:08,283 - sensors.Sensor       - INFO    - Binary sensor created / updated : alarmMode OFF
2024-01-06 16:25:08,288 - sensors.Sensor       - INFO    - Binary sensor created / updated : alarmTechnical OFF
2024-01-06 16:25:08,291 - sensors.Sensor       - INFO    - Binary sensor created / updated : alarmSOS OFF
2024-01-06 16:25:08,296 - sensors.Sensor       - INFO    - Binary sensor created / updated : unitAutoProtect OFF
2024-01-06 16:25:08,302 - sensors.Sensor       - INFO    - Binary sensor created / updated : unitBatteryDefect OFF
2024-01-06 16:25:08,307 - sensors.Sensor       - INFO    - Binary sensor created / updated : unackedEvent ON
2024-01-06 16:25:08,310 - sensors.Sensor       - INFO    - Binary sensor created / updated : systAutoProtect OFF
2024-01-06 16:25:08,314 - sensors.Sensor       - INFO    - Binary sensor created / updated : systBatteryDefect ON
2024-01-06 16:25:08,324 - sensors.Sensor       - INFO    - Binary sensor created / updated : systSupervisionDefect OFF
2024-01-06 16:25:08,331 - sensors.Sensor       - INFO    - Binary sensor created / updated : systOpenIssue OFF
2024-01-06 16:25:08,334 - sensors.Sensor       - INFO    - Binary sensor created / updated : systSectorDefect OFF
2024-01-06 16:25:08,337 - sensors.Sensor       - INFO    - Binary sensor created / updated : systTechnicalDefect OFF
2024-01-06 16:25:08,339 - sensors.Sensor       - INFO    - Binary sensor created / updated : videoLinkDefect OFF
2024-01-06 16:25:08,342 - sensors.Sensor       - INFO    - Binary sensor created / updated : remoteSurveyDefect OFF
2024-01-06 16:25:08,347 - sensors.Sensor       - INFO    - Binary sensor created / updated : simDefect OFF
2024-01-06 16:25:08,349 - sensors.Sensor       - INFO    - Binary sensor created / updated : networkDefect ON
2024-01-06 16:25:08,352 - sensors.Sensor       - INFO    - Binary sensor created / updated : inactiveProduct OFF
2024-01-06 16:25:08,355 - sensors.Sensor       - INFO    - Binary sensor created / updated : liveCheckRunning OFF
2024-01-06 16:25:08,358 - sensors.Sensor       - INFO    - Sensor created / updated : zone1State UNUSED
2024-01-06 16:25:08,361 - sensors.Sensor       - INFO    - Sensor created / updated : zone2State UNUSED
2024-01-06 16:25:08,365 - sensors.Sensor       - INFO    - Sensor created / updated : zone3State UNUSED
2024-01-06 16:25:08,368 - sensors.Sensor       - INFO    - Sensor created / updated : zone4State UNUSED
2024-01-06 16:25:08,372 - sensors.Sensor       - INFO    - Sensor created / updated : zone5State UNUSED
2024-01-06 16:25:08,375 - sensors.Sensor       - INFO    - Sensor created / updated : zone6State UNUSED
2024-01-06 16:25:08,378 - sensors.Sensor       - INFO    - Sensor created / updated : zone7State UNUSED
2024-01-06 16:25:08,382 - sensors.Sensor       - INFO    - Sensor created / updated : zone8State UNUSED
2024-01-06 16:25:08,385 - sensors.Sensor       - INFO    - Sensor created / updated : gsmLevel 7
2024-01-06 16:25:08,388 - sensors.Sensor       - INFO    - Sensor created / updated : irv1State AVAILABLE
2024-01-06 16:25:08,391 - sensors.Sensor       - INFO    - Sensor created / updated : irv2State UNAVAILABLE
2024-01-06 16:25:08,394 - sensors.Sensor       - INFO    - Sensor created / updated : irv3State UNAVAILABLE
2024-01-06 16:25:08,397 - sensors.Sensor       - INFO    - Sensor created / updated : irv4State UNAVAILABLE
2024-01-06 16:25:08,400 - sensors.Sensor       - INFO    - Binary sensor created / updated : kernelUpToDate ON
2024-01-06 16:25:08,406 - sensors.Alarm        - INFO    - Alarm created / updated : Tyxal Alarm 1698147441_1698147441 disarmed
2024-01-06 16:25:08,422 - tydom.MessageHandler - WARNING - Unknown message type received ([]
)
`

Bien lke bonjour, pour cette nouvelle année j'ai décider de rallumer mon raspberry pour essayer de connecter mon tydom et que je puisse mes tout mes équipements dessus volets box tv...

Je suis donc parti d'une installation à zéro donc réinstallation.
J'ai installer l'extension Tydom2mqtt et voici mon erreur en mode INFO 
Il indique bien sensor created mais ne voit rien du tout dans : entités (http://192.168.1.119:8123/config/entities)
Que faire ?
Merci beaucoup

**Comment by Shadorlo** [comment]
En ERROR j'ai ceci : 
`/app/tydom/TydomClient.py:312: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is "ACK":
2024-01-06 16:28:50,338 - Starting tydom2mqtt
2024-01-06 16:28:50,341 - Hassio environment detected: loading configuration from /data/options.json
2024-01-06 16:28:50,346 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "ERROR",
    "mqtt_host": "homeassistant",
    "mqtt_password": "p*************9",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "user123456798",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "mediation.tydom.com",
    "tydom_mac": "001A25020082",
    "tydom_password": "C******1"
}
2024-01-06 16:28:50,347 - The configuration is valid
2024-01-06 16:29:51,256 - __main__             - ERROR   - Websocket connection closed: received 1000 (OK); then sent 1000 (OK)`

**Comment by Shadorlo** [comment]
tydom2mqtt
Current version: 3.4.2 (Journal des modifications)

Si tu peux vraiment m'aider cela m'aiderai vraiment, j'ai vraiment envie de réutiliser Tydom
Je ne comprend plein de personnes y arrive sans problèmes mon installation possède un problème ou pas ??!
Je comprend bien que Tydom soit un peu mal foutu et vu le prix haha

**Comment by BlacKTM1190** [comment]
Hello

> "tydom_ip": "mediation.tydom.com"

Pourquoi ne pas utiliser l'ip local ? perso je n'ai jamais compris pourquoi passer par cette url pour revenir à la maison à fortiori quand l'ISP est down.

> "mqtt_password": "p*************9", "mqtt_port": 1883, "mqtt_ssl": false, "mqtt_user": "user123456798"

Es-tu sur des identifiants de connexion à ton broker mqtt ? peut être sont-ils bien renseignés mais pas utilisés.

**Comment by Shadorlo** [comment]
Oui c'est les bon identifiants je voit bien la connexion sur les logs 
J'ai utiliser cette url parce-que cela fonctionne avec haha

**Comment by Shadorlo** [comment]
Si tu veux m'aider en appel ou autre par exemple Discord je suis grand prenneur !

**Comment by BlacKTM1190** [comment]
Hello
Je n'ai pas discord...
Après relecture des logs que tu as fourni, il semble que ton soucis soit sensilement le même que #138.
