### ISSUE TITLE
Tydom2mqtt Current version: 3.4.3 - Add On unable to start at boot etc..

### ISSUE THREAD

**Issue by giagrand74** [fmartinou/tydom2mqtt#173]
Updated to version: 3.4.3
Add on not start at boot and if manually started after few it stops automatically.

2024-02-06 21:46:01,248 - Starting tydom2mqtt
2024-02-06 21:46:01,248 - Hassio environment detected: loading configuration from /data/options.json
2024-02-06 21:46:01,248 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "DEBUG",
    "mqtt_host": "homeassistant",
    "mqtt_password": "p******o",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "moscamoschina",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "192.168.1.67",
    "tydom_mac": "001A2501129B",
    "tydom_password": "P**********!",
    "tydom_polling_interval": 300
}
2024-02-06 21:46:01,248 - The configuration is valid
2024-02-06 21:46:01,249 - tydom.TydomClient    - DEBUG   - Initializing TydomClient Class
2024-02-06 21:46:01,249 - tydom.TydomClient    - INFO    - Configure local mode (192.168.1.67)
2024-02-06 21:46:01,250 - asyncio              - DEBUG   - Using selector: EpollSelector
2024-02-06 21:46:01,251 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=homeassistant, port=1883, user=moscamoschina, ssl=False)
2024-02-06 21:46:01,253 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-02-06 21:46:01,254 - __main__             - ERROR   - Connection refused ([Errno 111] Connection refused)
2024-02-06 21:46:01,259 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<poll_device_tydom() running at /app/main.py:73>>
/usr/local/lib/python3.11/asyncio/base_events.py:678: RuntimeWarning: coroutine 'poll_device_tydom' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2024-02-06 21:46:01,264 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<MqttClient.connect() done, defined at /app/mqtt/MqttClient.py:47> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()]>>
2024-02-06 21:46:01,264 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:42> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/app/main.py", line 46, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 138, in connect
    conn.request(
  File "/usr/local/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1459, in connect
    super().connect()
  File "/usr/local/lib/python3.11/http/client.py", line 952, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 70, in listen_tydom
    sys.exit(1)
SystemExit: 1
sys:1: RuntimeWarning: coroutine 'Client._resend_qos_messages' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2024-02-06 21:46:01,266 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Client._resend_qos_messages() running at /usr/local/lib/python3.11/site-packages/gmqtt/client.py:176>>

**Comment by giagrand74** [comment]
Core
2024.1.6
Supervisor
2024.01.1
Operating System
11.5
Frontend
20240104.0

**Comment by giagrand74** [comment]
2024-02-06 21:45:54.434 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Can't read stats from addon_6b64d821_tydom2mqtt: Expecting value: line 1 column 1 (char 0)
2024-02-06 21:45:54.435 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Can't read stats from addon_6b64d821_tydom2mqtt: Expecting value: line 1 column 1 (char 0)
2024-02-06 22:05:03.754 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Can't read stats from addon_6b64d821_tydom2mqtt: Expecting value: line 1 column 1 (char 0)
2024-02-06 22:05:04.950 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Can't read stats from addon_6b64d821_tydom2mqtt: Expecting value: line 1 column 1 (char 0)
2024-02-06 22:05:05.662 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Can't read stats from addon_6b64d821_tydom2mqtt: Expecting value: line 1 column 1 (char 0)
2024-02-06 22:05:19.432 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Container addon_6b64d821_tydom2mqtt is not running
2024-02-06 22:05:24.198 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Container addon_6b64d821_tydom2mqtt is not running
2024-02-06 22:05:43.837 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.core_mosquitto_outtemperature (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'C' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', 'K', '°F']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
2024-02-06 22:05:43.859 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.core_mosquitto_elec_a (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'VA' which is not a valid unit for the device class ('current') it is using; expected one of ['A', 'mA']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
2024-02-06 22:06:22.098 WARNING (Thread-5 (_thread_main)) [homeassistant.components.mqtt.client] Disconnected from MQTT server core-mosquitto:1883 (7)
2024-02-06 22:12:48.204 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/6b64d821_tydom2mqtt/stats - Container addon_6b64d821_tydom2mqtt is not running

**Comment by giagrand74** [comment]
Solved, Ip of the Tydom box was changed

**Comment by giagrand74** [comment]
Solved, Ip of the Tydom box was changed
