### ISSUE TITLE
Problem with the addon

### ISSUE THREAD

**Issue by catalane41** [fmartinou/tydom2mqtt#187]
Hi,
Sorry but I'm a beginner in Home Assistant and trying to implement the Tydom addon and i'm really in trouble. Could you please help.
Here is the log:

2024-03-28 19:16:23,311 - Starting tydom2mqtt
2024-03-28 19:16:23,312 - Hassio environment detected: loading configuration from /data/options.json
2024-03-28 19:16:23,316 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "INFO",
    "mqtt_host": "192.168.0.34",
    "mqtt_password": "2******e",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "mqtt",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "192.168.0.40",
    "tydom_mac": "001A25048459",
    "tydom_password": "A********$",
    "tydom_polling_interval": 300
}
2024-03-28 19:16:23,317 - The configuration is valid
2024-03-28 19:16:23,319 - tydom.TydomClient    - INFO    - Configure local mode (192.168.0.40)
2024-03-28 19:16:23,357 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=192.168.0.34, port=1883, user=mqtt, ssl=False)
2024-03-28 19:16:23,361 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-03-28 19:16:24,721 - mqtt.MqttClient      - INFO    - Connected to mqtt broker
2024-03-28 19:16:25,934 - tydom.TydomClient    - ERROR   - Exception when trying to connect with websocket (server rejected WebSocket connection: HTTP 401)
2024-03-28 19:16:25,993 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:42> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/app/tydom/TydomClient.py", line 187, in connect
    self.connection = await websockets.connect(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 325, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 46, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 198, in connect
    sys.exit(1)
SystemExit: 1
2024-03-28 19:16:26,090 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Client._resend_qos_messages() running at /usr/local/lib/python3.11/site-packages/gmqtt/client.py:181> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2024-03-28 19:16:26,093 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MQTTProtocol._read_loop() running at /usr/local/lib/python3.11/site-packages/gmqtt/mqtt/protocol.py:211> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2024-03-28 19:16:26,094 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<WebSocketCommonProtocol.close_connection() running at /usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py:1337> wait_for=<Future finished result=None>>
2024-03-28 19:16:26,095 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<poll_device_tydom() running at /app/main.py:76> wait_for=<Future pending cb=[Task.task_wakeup()]>>

Many thanks in advance
Regards
Edouard

**Comment by BlacKTM1190** [comment]
Hello,
`"tydom_password": "A**$"`
Are you sure it's your Tydom pwd not your DD account one ?
If so, change it to non special char one.
If not, set it to `"deltadore_password"` and give your `"deltadore_login"`, and leave blank your `"tydom_password"`.

**Comment by neilerua973** [comment]
See [my comment](https://github.com/fmartinou/tydom2mqtt/issues/209#issuecomment-2442317724)
