### ISSUE TITLE
Echec de connexion (ERROR   - Task exception was never retrieved)

### ISSUE THREAD

**Issue by jpmartin71** [fmartinou/tydom2mqtt#188]
Bonjour,
le pilotage de mes volet n'est plus possible depuis plusieurs jours.
La version de ma box TYDOM 1 est 03.15.31.
J'ai essayé de résoudre le problème en mettant à jour tydom2mqtt => 3.4.3
La connexion à la box ne semble plus fonctionné.

2024-03-31 07:33:21,668 - Starting tydom2mqtt
2024-03-31 07:33:21,669 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "DEBUG",
    "mqtt_host": "192.168.xxx.xxx",
    "mqtt_password": "xxxx",
    "mqtt_port": "xxxx",
    "mqtt_ssl": false,
    "mqtt_user": "xxxx",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "192.168.xxx.xxx",
    "tydom_mac": "xxxxxxxxxxx",
    "tydom_password": "xxxxxxxxx",
    "tydom_polling_interval": "60"
}
2024-03-31 07:33:21,670 - The configuration is valid
2024-03-31 07:33:21,670 - tydom.TydomClient    - DEBUG   - Initializing TydomClient Class
2024-03-31 07:33:21,671 - tydom.TydomClient    - INFO    - Configure local mode (192.168.0.xxx)
2024-03-31 07:33:21,677 - asyncio              - DEBUG   - Using selector: EpollSelector
2024-03-31 07:33:21,679 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=192.168.xxx.xxx, port=xxxx, user=xxxx, ssl=False)
2024-03-31 07:33:21,681 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-03-31 07:33:28,466 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:42> exception=RemoteDisconnected('Remote end closed connection without response')>
Traceback (most recent call last):
  File "/app/main.py", line 46, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 144, in connect
    res = conn.getresponse()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1386, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
2024-03-31 07:33:28,473 - gmqtt.mqtt.protocol  - INFO    - [CONNECTION MADE]
2024-03-31 07:33:28,474 - gmqtt.client         - DEBUG   - [CMD 0x20] b'\x00\x00\x06"\x00\n!\x00\x14'
2024-03-31 07:33:28,475 - gmqtt.client         - DEBUG   - [CONNACK] flags: 0x0, result: 0x0
2024-03-31 07:33:28,475 - mqtt.MqttClient      - DEBUG   - Subscribing to topics (+/tydom/#)
2024-03-31 07:33:28,476 - gmqtt.mqtt.utils     - DEBUG   - NEW ID: 1
2024-03-31 07:33:28,476 - gmqtt.mqtt.package   - INFO    - [SEND SUB] 1 [b'homeassistant/status']
2024-03-31 07:33:28,477 - gmqtt.mqtt.utils     - DEBUG   - NEW ID: 2
2024-03-31 07:33:28,477 - gmqtt.mqtt.package   - INFO    - [SEND SUB] 2 [b'+/tydom/#']
2024-03-31 07:33:28,478 - gmqtt.client         - DEBUG   - [QoS query IS EMPTY]
2024-03-31 07:33:28,478 - mqtt.MqttClient      - INFO    - Connected to mqtt broker

Si vous avez une piste je vous en remercie.

**Comment by Eoras** [comment]
J’ai eu ce soucis, le mot de passe de ton materiel n’est plus bon il a du changé lors d’une mise à jour de ta passerelle. 

Si tu veux pas t’embêter tu peux mettre ton e-mail et mot de passe de ton application Tydom dans les configurations de Tydom2Mqtt (tout en bas tu coche : configuration non utilisée et tu renseigner ça). Il va aller chercher le mot de passe de ta box directement en te connectant. Ainsi tu n’auras plus ce problème.

**Comment by TheDjGogo2000** [comment]
Bonjour,

comme @jpmartin71 , j'ai des soucis de connexion : 
`2024-04-01 12:11:23,141 - Starting tydom2mqtt
2024-04-01 12:11:23,142 - Hassio environment detected: loading configuration from /data/options.json
2024-04-01 12:11:24,697 - Validating configuration ({
    "deltadore_login": "xxxx@xxx.com",
    "deltadore_password": "P*************s",
    "log_level": "INFO",
    "mqtt_host": "192.168.0.29",
    "mqtt_password": "o**************************************************************t",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "homeassistant",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "192.168.0.45",
    "tydom_mac": "001A25xxxxxx",
    "tydom_password": "M********9",
    "tydom_polling_interval": 300
}
2024-04-01 12:11:24,698 - The configuration is valid
2024-04-01 12:11:24,698 - tydom.TydomClient    - INFO    - Configure local mode (192.168.0.45)
2024-04-01 12:11:24,703 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=192.168.0.29, port=1883, user=homeassistant, ssl=False)
2024-04-01 12:11:24,704 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-04-01 12:11:24,712 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:42> exception=SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')>
Traceback (most recent call last):
  File "/app/main.py", line 46, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 138, in connect
    conn.request(
  File "/usr/local/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1466, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
2024-04-01 12:11:24,726 - mqtt.MqttClient      - INFO    - Connected to mqtt broker`

**Comment by TheDjGogo2000** [comment]
a tydom1 reboot has resolved my problem. 
un redémarrage de Tydom1 a résolu mon problème

**Comment by jpmartin71** [comment]
Bonjour,
merci @Eoras et @TheDjGogo2000 
1/ j'ai redémarré ma Tydom => connexion KO
2/ j'ai ajouté mes identifiants Deltadore et redémarré mon container tydom2mqtt => connexion KO
3/ j'ai redémarré me Tydom et mon container tydom2mqtt => joie bonheur la connexion et le contrôle de mes volets est revenu.

Hello,
thanks @Eoras and @TheDjGogo2000 
1/ I restarted my Tydom => connection KO
2/ I added my Deltadore credentials and restarted my container tydom2mqtt => connection KO
3/ I restarted my Tydom and my container tydom2mqtt => happy connection and control of my shutters is back.

**Comment by Romain-76** [comment]
Hello, same issue here since about 2 months. I have a Tydom 2 (with Tyxal alarm indeed). This issue happens every 10 days, then I just need to restart the integration to get it work. and after 3 additionnal days the error come back and after that the only solution is to dismount the Tydom 2 to remove the battery and shutdown power. And after I reboot, I'm ok for about 10 days, etc.

Using mediation.tydom.com is not an alternative for me as I need to get status of the alarm and the refresh is not accurate from mediation.tydom.com.

I have tried with an older version of the addon (when it was working before) and same issue.

I am using tydom2mqtt since it was a beta and never had any issue in 4 years... 

Here is my log, let me know if I should share any other log : 

2024-06-01 09:41:24,614 - Starting tydom2mqtt
2024-06-01 09:41:24,615 - Hassio environment detected: loading configuration from /data/options.json
2024-06-01 09:41:26,144 - Validating configuration ({
    "deltadore_login": "XXX@XXX.fr",
    "deltadore_password": "***********",
    "log_level": "INFO",
    "mqtt_host": "homeassistant",
    "mqtt_password": "*******",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "mqtt",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "******",
    "tydom_ip": "192.168.2.10",
    "tydom_mac": "*****",
    "tydom_password": "***********",
    "tydom_polling_interval": 300
}
2024-06-01 09:41:26,144 - The configuration is valid
2024-06-01 09:41:26,145 - tydom.TydomClient    - INFO    - Configure local mode (192.168.2.10)
2024-06-01 09:41:26,148 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=homeassistant, port=1883, user=mqtt, ssl=False)
2024-06-01 09:41:26,159 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-06-01 09:41:26,163 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:42> exception=SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')>
Traceback (most recent call last):
  File "/app/main.py", line 46, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 138, in connect
    conn.request(
  File "/usr/local/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1466, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
2024-06-01 09:41:26,256 - mqtt.MqttClient      - INFO    - Connected to mqtt broker

Thanks in advance !

**Comment by TheDjGogo2000** [comment]
Bonjour,

Tout les 10 jours en moyenne, tydom2mqtt ne fonctionne plus. Seule solution, redémarrer le boitier Tydom1.0
(si j'utilise GoogleHome connecté directement à Tydom ça fonctionne, l'appli Tydom fonctionne également, ainsi que les commandes locales (interrupteurs))

Ma config :
HA Core 2024.6.4
Supervisor 2024.06.2
mosquitto 6.4.1
tydom2mqtt : 3.5.2

Log de Tydom2Mqtt :

2024-07-17 10:50:39,978 - gmqtt.mqtt.protocol  - WARNING - [TRYING WRITE TO CLOSED SOCKET]
2024-07-17 10:50:47,493 - gmqtt.mqtt.protocol  - WARNING - [TRYING WRITE TO CLOSED SOCKET]
2024-07-17 10:50:53,838 - gmqtt.mqtt.protocol  - WARNING - [TRYING WRITE TO CLOSED SOCKET]
2024-07-17 10:50:59,929 - gmqtt.client         - WARNING - [CAN'T RECONNECT] 1
2024-07-17 10:50:59,943 - gmqtt.mqtt.protocol  - WARNING - [TRYING WRITE TO CLOSED SOCKET]
2024-07-17 10:51:08,196 - gmqtt.mqtt.protocol  - WARNING - [EXC: CONN LOST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-07-17 10:51:08,344 - gmqtt.mqtt.protocol  - WARNING - [TRYING WRITE TO CLOSED SOCKET]
2024-07-17 10:51:14,356 - gmqtt.mqtt.protocol  - WARNING - [TRYING WRITE TO CLOSED SOCKET]
2024-07-17 10:51:26,562 - tydom.TydomClient    - WARNING - Cannot send message to Tydom because no connection has been established yet
2024-07-17 10:51:52,023 - Starting tydom2mqtt
2024-07-17 10:51:52,033 - Hassio environment detected: loading configuration from /data/options.json
2024-07-17 10:51:56,209 - Validating configuration ({
    "deltadore_login": "D***@**.com",
    "deltadore_password": "P*************s",
    "log_level": "WARNING",
    "mqtt_host": "192.168.0.**",
    "mqtt_password": "o**************************************************************t",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "homeassistant",
    "thermostat_cool_mode_temp_default": 26,
    "thermostat_custom_presets": null,
    "thermostat_heat_mode_temp_default": 16,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "192.168.0.**",
    "tydom_mac": "001*******C",
    "tydom_password": "M********9",
    "tydom_polling_interval": 300
}
2024-07-17 10:51:56,210 - The configuration is valid
2024-07-17 10:51:56,251 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:42> exception=SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')>
Traceback (most recent call last):
  File "/app/main.py", line 46, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 145, in connect
    conn.request(
  File "/usr/local/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1466, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006


En espérant que ça peut aider à dépanner.

**Comment by gypais** [comment]
meme probleme : redémarrage de tydom2mqtt et de tydom box et c'est revenu

**Comment by sofmanb** [comment]
j'ai le meme probleme et je dois redemarrer regulierement le module tydom2mqtt c'est penible. Qqun a trouver une solution plus pereine?

**Comment by pTibar** [comment]
Bonjour même problème chez moi, y a t'il une solution ? Merci.
