### ISSUE TITLE
La configuration MQTT n'est plus prise en compte

### ISSUE THREAD

**Issue by BadarouxY** [fmartinou/tydom2mqtt#192]
Bonjour,

depuis la mise à jour 3.5 de cet après-midi, plus rien ne marche. Je rencontre l'erreur suivante ci-dessous. J'ai regardé rapidement les différences avec la version antérieure, et j'ai un doute que cela vienne bien de ça, mais je préfère demander.

```
2024-06-07 23:42:13,428 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-06-07 23:42:17,308 - mqtt.MqttClient      - WARNING - MQTT connection error : Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 1883), [Errno 99] Address not available
2024-06-07 23:42:21,013 - tydom.TydomClient    - INFO    - Connected to tydom
2024-06-07 23:42:21,013 - tydom.TydomClient    - INFO    - Setup tydom client
2024-06-07 23:42:21,224 - tydom.MessageHandler - INFO    - Device update (id=1696450151, endpoint=1696450151, name=Bureau 2, type=shutter)
2024-06-07 23:42:21,225 - tydom.MessageHandler - ERROR   - Error on parsing tydom response ('NoneType' object has no attribute 'publish')
2024-06-07 23:42:21,225 - tydom.MessageHandler - ERROR   - Incoming data ([{"id":1696450151,"endpoints":[{"id":1696450151,"error":0,"data":[_{"name":"thermicDefect","validity":"upToDate","value":false},{"name":"position","validity":"upToDate","value":0},{"name":"onFavPos","validity":"upToDate","value":false},{"name":"upDefect","validity":"upToDate","value":false},{"name":"downDefect","validity":"upToDate","value":false},{"name":"obstacleDefect","validity":"upToDate","value":false},{"name":"intrusion","validity":"upToDate","value":false},{"name":"battDefect","validity":"upToDate","value":false}]}]}_,XXXX...(tout est conforme, je me permet de raccourcir le json)]
)
2024-06-07 23:42:21,226 - tydom.MessageHandler - ERROR   - 'NoneType' object has no attribute 'publish'
Traceback (most recent call last):
  File "/app/tydom/MessageHandler.py", line 363, in parse_response
    await self.parse_devices_data(parsed=parsed)
  File "/app/tydom/MessageHandler.py", line 473, in parse_devices_data
    await self.parse_endpoint_data(endpoint, i["id"])
  File "/app/tydom/MessageHandler.py", line 687, in parse_endpoint_data
    await new_cover.update()
  File "/app/sensors/Cover.py", line 73, in update
    await self.setup()
  File "/app/sensors/Cover.py", line 68, in setup
    self.mqtt.mqtt_client.publish(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish'
2024-06-07 23:42:21,233 - tydom.MessageHandler - WARNING - Unknown message type received ([]
)
2024-06-07 23:56:21,797 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Client._resend_qos_messages() running at /usr/local/lib/python3.11/site-packages/gmqtt/client.py:177> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

D'avance merci

**Comment by fmartinou** [comment]
Ça m'a été remonté il y a quelques heures effectivement.
La config Mqtt ne serait plus prise en compte 

https://github.com/fmartinou/hassio-addons/issues/19#issuecomment-2155563485

La seule différence provient d'une pr qui a été acceptée ; reste à trouver la cause. Je regarderai ça demain.

**Comment by fmartinou** [comment]
Une version  `3.5.1` qui devrait corriger le problème vient d'être releasée.

**Comment by BadarouxY** [comment]
> Une version `3.5.1` qui devrait corriger le problème vient d'être releasée.

Merci beaucoup pour ta réactivité (et celle de la communauté) et surtout pour ton précieux travail d'ensemble sur ce sujet, vraiment utile.

**Comment by BadarouxY** [comment]
Je ferme, après test c'est tout bon. Merci
