### ISSUE TITLE
Error Connection SSL did not do anything and today no connection 

### ISSUE THREAD

**Issue by sosso-b** [fmartinou/tydom2mqtt#212]
this is the code error

2024-10-06 12:11:23,089 - The configuration is valid
2024-10-06 12:11:23,090 - tydom.TydomClient    - INFO    - Configure local mode (192.168.1.162)
2024-10-06 12:11:23,094 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=homeassistant, port=1883, user=mqtt-soba, ssl=False)
2024-10-06 12:11:23,106 - tydom.TydomClient    - INFO    - Connecting to tydom
2024-10-06 12:11:23,111 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:42> exception=SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')>
Traceback (most recent call last):
  File "/app/main.py", line 46, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 145, in connect
    conn.request(
  File "/usr/local/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1466, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
2024-10-06 12:11:23,124 - mqtt.MqttClient      - INFO    - Connected to mqtt broker

**Comment by sosso-b** [comment]
To solve that i just restart the tydom box and restart tydom2mqtt and everything work again like a charm i close this issue
