### ISSUE TITLE
'set_position_topic' must be set together with 'position_topic'

### ISSUE THREAD

**Issue by birse29** [fmartinou/tydom2mqtt#34]
Hello,

This morning my docker image got updated by watchtower with latest release this morning and now covers are not longer available in Home Assistant. In fact, the device position_tydom_<DEVICE> got well updated but not the <DEVICE> itself.

Logs for the device "Volet_Bureau":
2022-09-04 09:03:37,197 - sensors - INFO - Sensor created / updated : device_id_tydom__Volet_Bureau 1611312665
2022-09-04 09:03:37,197 - sensors - INFO - Sensor created / updated : endpoint_id_tydom__Volet_Bureau 1611312665
2022-09-04 09:03:37,197 - sensors - INFO - Sensor created / updated : id_tydom__Volet_Bureau 1611312665_1611312665
2022-09-04 09:03:37,197 - sensors - INFO - Sensor created / updated : position_tydom__Volet_Bureau 0
2022-09-04 09:03:37,197 - cover - INFO - Cover created / updated : Volet Bureau 1611312665_1611312665

HA Logs for this device:
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Volet Bureau', 'unique_id': '1611312665_1611312665', 'command_topic': 'cover/tydom/1611312665_1611312665/set_positionCmd', 'set_position_topic': 'cover/tydom/1611312665_1611312665/set_position', 'json_attributes_topic': 'cover/tydom/1611312665_1611312665/attributes', 'payload_open': 'UP', 'payload_close': 'DOWN', 'payload_stop': 'STOP', 'retain': 'false', 'device': {'manufacturer': 'Delta Dore', 'model': 'Volet', 'name': 'Volet Bureau', 'identifiers': '1611312665_1611312665'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 123, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'set_position_topic' must be set together with 'position_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 323, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'set_position_topic' must be set together with 'position_topic'.

**Comment by fmartinou** [comment]
Hi,

Sorry for the regression.

@erichard; may you take a look at this one, please?
It has been caused by your changes for supporting sunshade covers.

N.B.
@birse29, just an advice; do not rely on `latest` tags with Docker; it's too risky ;)
Better use `semver` tags only and update your containers in total control.

Watchtower doesn't support that but others do, like:
- [What's up Docker?](https://fmartinou.github.io/whats-up-docker/#/) (self-promotion 😁 )
- [Diun](https://crazymax.dev/diun/)

++

**Comment by erichard** [comment]
@birse29 `position_topic` should be set if the cover report its position. Strange you have this error. I will check shortly.

**Comment by birse29** [comment]
@erichard I rollbacked to release 2.2.0 and it works again in HA. Tell me if I can help somehow ?
@fmartinou Yes it is risky but that's ok for my personal use

**Comment by cob94440** [comment]
Same for me.
Since last update today, evrything seems fine in tydom logs. However my covers are unavailable from HA.
No problem with doors sensor i think

**Comment by BlacKTM1190** [comment]
Hello
No problem for me but i'm on Jeedom.
Wouldn't that be an issu on assio addon ?

**Comment by cob94440** [comment]
maybe linked with :
`🔥 Fix binary sensors created but not updated on HA`

**Comment by erichard** [comment]
I can't get any further with the device I have. I need to see the data your covers send. 

You can get these by installing the nodeJS tydom-client with 
```
npm install -g tydom-client
```
and then run the following command
```
npx tydom-client request  /devices/data   --username <MAC_ADDRESS> --password <PASSWORD> --file output.json
```
