### ISSUE TITLE
Add-on crashes daily at 3:15am

### ISSUE THREAD

**Issue by jerry34ha** [fmartinou/tydom2mqtt#46]
Hi,

for an unknown reason, the add-on restarts every night between 2:30am and 3:30am.

The restart fails with the following error:

```
2022-10-04 03:15:07,181 - tydomConnector - INFO - Host Target : mediation.tydom.com
2022-10-04 03:15:07,285 - gmqtt.mqtt.handler - INFO - [SUBACK] 1 (0,)
2022-10-04 03:15:07,288 - gmqtt.mqtt.handler - INFO - [SUBACK] 2 (0,)
2022-10-04 03:15:07,416 - __main__ - INFO - Tydom Client is connected to websocket and ready !
2022-10-04 03:15:07,420 - tydomConnector - INFO - Requesting 1st data...
2022-10-04 03:15:07,423 - tydomConnector - INFO - >>>>>>>>>> Sending to tydom client..... GET /info
2022-10-04 03:15:07,430 - tydomConnector - INFO - ##################################
2022-10-04 03:15:07,434 - tydomConnector - INFO - ##################################
2022-10-04 03:15:07,437 - tydomConnector - INFO - >>>>>>>>>> Sending to tydom client..... POST /refresh/all
2022-10-04 03:15:07,442 - tydomConnector - INFO - >>>>>>>>>> Sending to tydom client..... GET /configs/file
2022-10-04 03:15:07,447 - tydomConnector - INFO - >>>>>>>>>> Sending to tydom client..... GET /devices/cmeta
2022-10-04 03:15:12,458 - tydomConnector - INFO - >>>>>>>>>> Sending to tydom client..... GET /devices/data
Traceback (most recent call last):
  File "/app/main.py", line 226, in <module>
    loop_task()
  File "/app/main.py", line 148, in loop_task
    loop.run_until_complete(listen_tydom_forever(tydom_client))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/app/main.py", line 162, in listen_tydom_forever
    await tydom_client.setup()
  File "/app/tydomConnector.py", line 438, in setup
    await self.get_data()
  File "/app/tydomConnector.py", line 409, in get_data
    await self.get_devices_data()
  File "/app/tydomConnector.py", line 386, in get_devices_data
    await self.send_message(method=req, msg=msg_type)
  File "/app/tydomConnector.py", line 243, in send_message
    await self.connection.send(a_bytes)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 620, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 4001 (private use) Tydom non connecté.; then sent 4001 (private use) Tydom non connecté.
```
After that,
Manually restarting the add-on does not fix the problem.
Rebooting the HAss virtual machine does not fix the problem.
Restarting TYDOM box does fix the problem until the next night at around 2:00am when it happens again.

There is no particular message at that moment in home-assistant.log

If you tell me how to collect more logs for mqtt2tydom, I will give you more logs (as currently I only see the restart phase in the add-on log page. I don't see the event that that triggered the restart).

**Comment by fmartinou** [comment]
Are you using the public mediation endpoint or the local ip address?

**Comment by jerry34ha** [comment]
Tydom IP address: mediation.tydom.com

By the way, the Tydom is probably crashed at this stage because its light is solid orange.

So the add-on provokes an issue with the Tydom 1.0. In the last 2 years before I started experimenting with HA, it did not crash once.

**Comment by arnodu** [comment]
I have a similar issue with my Tydom Home : 
At some point (every day or so, not at a particular time) my power graphs stop updating in my home assistant, tydom2mqtt has stopped because it could not connect, and my tydom Home box lights up in orange. The tydom app doesn't connect either.

I also use mediation.tydom.com for TYDOM_IP . Is there any known issues with mediation.tydom.com ?

Did not occur to me so far that it could be a connection issue with the delta dore servers. Next time it happens, i'll try to use the local IP to connect to the tydom when it goes into "orange mode". The delta dore manual says solid orange means "local only" by the way (whatever it means).

**Comment by arnodu** [comment]
So, my Tydom crashed again today. A few symptoms : 

* Solid orange light
* on mediation.tydom.com : No error in the tydom2mqtt log, but no update on energy sensors
* I switch to the local IP and i get this error : 
 
```
2022-10-10 21:30:45,994 - tydomConnector - INFO - """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
2022-10-10 21:30:45,995 - tydomConnector - INFO - TYDOM WEBSOCKET CONNECTION INITIALISING....                     
2022-10-10 21:30:45,995 - tydomConnector - INFO - Building headers, getting 1st handshake and authentication....
Traceback (most recent call last):
  File "/app/main.py", line 226, in <module>
    loop_task()
  File "/app/main.py", line 148, in loop_task
    loop.run_until_complete(listen_tydom_forever(tydom_client))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/app/main.py", line 160, in listen_tydom_forever
    await tydom_client.connect()
  File "/app/tydomConnector.py", line 108, in connect
    conn.request(
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
```

* https://\<local tydom ip\> displays : 
![image](https://user-images.githubusercontent.com/6960430/194940359-6a9649ff-0e93-4cf9-8bc0-6347419e9f19.png)

* I restart the tydom : the web interface comes back, tydom2mqtt connects to the local IP, everything works

**Comment by arnodu** [comment]
Update: I used the local IP instead of mediation.tydom.com and i had no crash since my last post.

**Comment by jerry34ha** [comment]
A year later I tried again. I'm on 3.4.2 and it is not happening anymore. Closing.
