### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by Pmachat** [fmartinou/tydom2mqtt#53]
Bonjour,
Je ne connais pas trop docker. Je suis plutot habituer à faire des installations directement sur mon RPi
Quand je lance "sudo docker-compose up" après avoir configurer mon fichier, le process ne se lance pas et j'ai l'eereur suivante
tydom2mqtt    | Traceback (most recent call last):
tydom2mqtt    |   File "/app/main.py", line 2, in <module>
tydom2mqtt    |     import asyncio
tydom2mqtt    |   File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
tydom2mqtt    |     from .base_events import *
tydom2mqtt    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
tydom2mqtt    |     import concurrent.futures
tydom2mqtt    |   File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
tydom2mqtt    |     from concurrent.futures._base import (FIRST_COMPLETED,
tydom2mqtt    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
tydom2mqtt    |     import logging
tydom2mqtt    |   File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
tydom2mqtt    |     _startTime = time.time()
tydom2mqtt    | PermissionError: [Errno 1] Operation not permitted

Je suppose que cela vient peut-etre de mon installation  deocker 

Avez-vous une idée ?

Merci d'avance

PM

Mon fichier config
version: '3'
services:
  tydom2mqtt:
    image: fmartinou/tydom2mqtt
    container_name: tydom2mqtt
    environment:
      - TYDOM_MAC=001A25xxxxxx
      - TYDOM_PASSWORD=
      - TYDOM_IP=192.168.x.x
      - MQTT_HOST=192.168.y.y
      - MQTT_PORT=port
      - MQTT_USER=user
      - MQTT_PASSWORD=pass

**Comment by Pmachat** [comment]
Bonjour

En ajoutant dans le fichier de config
   privileged: true
Cela fonctionne.

Je ne sais pas trop le pourquoi et les conséquences, mais ca marche !
