### ISSUE TITLE
Tydom error

### ISSUE THREAD

**Issue by Shadorlo** [fmartinou/tydom2mqtt#87]
Hello voici mes logs si besoin voici mon discord je répond plus vite ^^ 
**Discord: Shadorlo#5203**

`2023-03-25 21:48:37,803 - Starting tydom2mqtt
2023-03-25 21:48:37,805 - Hassio environment detected: loading configuration from /data/options.json
2023-03-25 21:48:37,807 - Validating configuration ({
    "log_level": "DEBUG",
    "mqtt_host": "192.168.1.72",
    "mqtt_password": "p****d",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "user",
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "192.168.1.27",
    "tydom_mac": "001A25020082",
    "tydom_password": "T************"
}
2023-03-25 21:48:37,808 - The configuration is valid
2023-03-25 21:48:37,809 - tydom.TydomClient    - DEBUG   - Initializing TydomClient Class
2023-03-25 21:48:37,810 - tydom.TydomClient    - INFO    - Configure local mode (192.168.1.27)
2023-03-25 21:48:37,819 - asyncio              - DEBUG   - Using selector: EpollSelector
2023-03-25 21:48:37,824 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=192.168.1.72, port=1883, user=user, ssl=False)
2023-03-25 21:48:37,828 - tydom.TydomClient    - INFO    - Connecting to tydom
2023-03-25 21:48:39,024 - tydom.TydomClient    - DEBUG   - Response headers
2023-03-25 21:48:39,024 - tydom.TydomClient    - DEBUG   - Connection: close
WWW-Authenticate: Digest realm="Protected Area", qop="auth", nonce="840b0c660f77b587fbd4a9c2953e636e", opaque="572ca016a1c92e43e7dbbbd80eaec598"
Content-Type: text/html
2023-03-25 21:48:39,064 - tydom.TydomClient    - DEBUG   - Response code
2023-03-25 21:48:39,064 - tydom.TydomClient    - DEBUG   - 401
2023-03-25 21:48:39,065 - tydom.TydomClient    - DEBUG   - response
2023-03-25 21:48:39,067 - tydom.TydomClient    - DEBUG   - b'<!doctype html>\r\n<html>\r\n<head><title>Error 401</title></head>\r\n<body>\r\n<h2>Error 401</h2>\r\n<p>Authorization required</p>\r\n</body>\r\n</html>\r\n'
2023-03-25 21:48:39,069 - tydom.TydomClient    - DEBUG   - Upgrading http connection to websocket....
2023-03-25 21:48:39,069 - tydom.TydomClient    - DEBUG   - Attempting websocket connection with Tydom hub
2023-03-25 21:48:39,150 - mqtt.MqttClient      - WARNING - MQTT connection error : [Errno 111] Connect call failed ('192.168.1.72', 1883)
2023-03-25 21:48:39,152 - websockets.client    - DEBUG   - = connection is CONNECTING
2023-03-25 21:48:40,390 - websockets.client    - DEBUG   - > GET /mediation/client?mac=001A25020082&appli=1 HTTP/1.1
2023-03-25 21:48:40,391 - websockets.client    - DEBUG   - > Host: 192.168.1.27
2023-03-25 21:48:40,392 - websockets.client    - DEBUG   - > Upgrade: websocket
2023-03-25 21:48:40,393 - websockets.client    - DEBUG   - > Connection: Upgrade
2023-03-25 21:48:40,394 - websockets.client    - DEBUG   - > Sec-WebSocket-Key: +XEOl2O9IrL0KEfpA5puww==
2023-03-25 21:48:40,395 - websockets.client    - DEBUG   - > Sec-WebSocket-Version: 13
2023-03-25 21:48:40,396 - websockets.client    - DEBUG   - > Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
2023-03-25 21:48:40,397 - websockets.client    - DEBUG   - > Authorization: Digest username="001A25020082", realm="protected area", nonce="840b0c660f77b587fbd4a9c2953e636e", uri="/mediation/client?mac=001A25020082&appli=1", response="467ccaa1fd045b46a66a4a4ed36b6b52", qop="auth", nc=00000001, cnonce="c3c8b6a94c85b9c9"
2023-03-25 21:48:40,398 - websockets.client    - DEBUG   - > User-Agent: Python/3.11 websockets/10.4
2023-03-25 21:48:40,406 - websockets.client    - DEBUG   - < HTTP/1.1 401 Unauthorized
2023-03-25 21:48:40,407 - websockets.client    - DEBUG   - < Connection: close
2023-03-25 21:48:40,408 - websockets.client    - DEBUG   - < WWW-Authenticate: Digest realm="Protected Area", qop="auth", nonce="58c02ea066e3cf9f251686e930252e8b", opaque="8739ae08fd9dd48c0588a3277cefb10e"
2023-03-25 21:48:40,408 - websockets.client    - DEBUG   - < Content-Type: text/html
2023-03-25 21:48:40,409 - websockets.client    - DEBUG   - ! failing connection with code 1006
2023-03-25 21:48:40,411 - websockets.client    - DEBUG   - x closing TCP connection
2023-03-25 21:48:40,415 - websockets.client    - DEBUG   - = connection is CLOSED
2023-03-25 21:48:40,416 - tydom.TydomClient    - ERROR   - Exception when trying to connect with websocket (server rejected WebSocket connection: HTTP 401)
2023-03-25 21:48:40,468 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Client._resend_qos_messages() running at /usr/local/lib/python3.11/site-packages/gmqtt/client.py:177> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2023-03-25 21:48:40,469 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:41> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/app/tydom/TydomClient.py", line 117, in connect
    self.connection = await websockets.connect(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 44, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 128, in connect
    sys.exit(1)
SystemExit: 1`

**Comment by Shadorlo** [comment]
je me fais également spammer de log dans les paramètres de home assistant voici l'erreur

Logger: frontend.js.latest.202303091
Source: components/system_log/__init__.py:254
First occurred: 21:43:31 (19 occurrences)
Last logged: 21:55:17

http://xxxxxx:8123/config/dashboard:0:0 Uncaught
http://xxxxxx:8123/hassio/addon/9afc8f77_tydom2mqtt/info:0:0 Uncaught
http://xxxxxx:8123/hassio/addon/9afc8f77_tydom2mqtt/config:0:0 Uncaught
http://xxxxxx:8123/config/logs:0:0 Uncaught

**Comment by Shadorlo** [comment]
Hello, my latest error log:

`2023-03-26 00:38:52,375 - Starting tydom2mqtt
2023-03-26 00:38:52,377 - Hassio environment detected: loading configuration from /data/options.json
2023-03-26 00:38:52,379 - Validating configuration ({
    "log_level": "INFO",
    "mqtt_host": "192.168.1.72",
    "mqtt_password": "m***t",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "mqqqt",
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "192.168.1.27",
    "tydom_mac": "MAC",
    "tydom_password": "T************"
}
2023-03-26 00:38:52,380 - The configuration is valid
2023-03-26 00:38:52,381 - tydom.TydomClient    - INFO    - Configure local mode (192.168.1.27)
2023-03-26 00:38:52,395 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=192.168.1.72, port=1883, user=mqqqt, ssl=False)
2023-03-26 00:38:52,399 - tydom.TydomClient    - INFO    - Connecting to tydom
2023-03-26 00:38:53,703 - mqtt.MqttClient      - INFO    - Connected to mqtt broker
2023-03-26 00:38:54,893 - tydom.TydomClient    - ERROR   - Exception when trying to connect with websocket (server rejected WebSocket connection: HTTP 401)
2023-03-26 00:38:54,945 - asyncio              - ERROR   - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<listen_tydom() done, defined at /app/main.py:41> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/app/tydom/TydomClient.py", line 117, in connect
    self.connection = await websockets.connect(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 44, in listen_tydom
    await tydom_client.connect()
  File "/app/tydom/TydomClient.py", line 128, in connect
    sys.exit(1)
SystemExit: 1
2023-03-26 00:38:55,037 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Client._resend_qos_messages() running at /usr/local/lib/python3.11/site-packages/gmqtt/client.py:181> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2023-03-26 00:38:55,039 - asyncio              - ERROR   - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MQTTProtocol._read_loop() running at /usr/local/lib/python3.11/site-packages/gmqtt/mqtt/protocol.py:211> wait_for=<Future pending cb=[Task.task_wakeup()]>>`

**Comment by Shadorlo** [comment]
For information I use Home Assistant OS all my devices are connected on the same network in ethernet I opened the ports requested

**Comment by Shadorlo** [comment]
How to solve this problem? 2023-03-26 01:56:26,199 - main - WARNING - Unable to handle message: received 1000 (OK); then sent 1000 (OK)

**Comment by Shadorlo** [comment]
I don't use the local ip to connect to it

**Comment by KeepYourITUp** [comment]
> How to solve this problem? 2023-03-26 01:56:26,199 - main - WARNING - Unable to handle message: received 1000 (OK); then sent 1000 (OK)

I have the same problem.
 WARNING - Unable to handle message: received 1000 (OK); then sent 1000 (OK)

Sometimes it works and the temperature gets set and highlighted back in a black font, sometimes it fails and the temperature stays highlighted in red. I'm using the local ip address of my tydom v1.
Any ideas? I have already updated to the latest version. All versions in the past have had the problem where I'm not always 100% sure if the temperature will be set or not. Sometimes it works and sometimes it fails.

**Comment by NODRAP63** [comment]
> > How to solve this problem? 2023-03-26 01:56:26,199 - main - WARNING - Unable to handle message: received 1000 (OK); then sent 1000 (OK)
> 
> I have the same problem. WARNING - Unable to handle message: received 1000 (OK); then sent 1000 (OK)
> 
> Sometimes it works and the temperature gets set and highlighted back in a black font, sometimes it fails and the temperature stays highlighted in red. I'm using the local ip address of my tydom v1. Any ideas? I have already updated to the latest version. All versions in the past have had the problem where I'm not always 100% sure if the temperature will be set or not. Sometimes it works and sometimes it fails.

I also have the problem, it seems to be more frequent on the last version. does anyone have an idea ?

**Comment by KeepYourITUp** [comment]
Hi,
Thanks for the suggestion but the configuration was already set to the local ip.
I tried both the local ip and mediation.tydom.com but it still gives the same error.

I get the errors below:
WARNING - Unable to handle message: received 1000 (OK); then sent 1000 (OK)
WARNING - Unable to handle message: no close frame received or sent

Any idea?
When I restart the Tydom add-on it usually works again for x minutes/hours.

**Comment by Shadorlo** [comment]
Hey, have you made it since?
