### ISSUE TITLE
Probleme Entites Tywatt 

### ISSUE THREAD

**Issue by Muspi** [fmartinou/tydom2mqtt#88]
Bonjour,

Depuis quelques jours, je n'ai plus les informations qui remontent des entités tywatt.
Elles n'apparaissent plus dans les logs visiblement.
Je précise que ma configurtion n'a pas chang, et tydom n'a pas été mis à jour.
Tydom2mqtt est configuré pour se mettre à jour automatiquement. 

Est ce qu'il y a eu une release susceptible de les faire disfonctionner?

**Comment by NCoiby** [comment]
Seulement HA.

**Comment by Muspi** [comment]
OK, merci, je teste

**Comment by Muspi** [comment]
J'ai cette erreur maintenant

` record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 119, in <module>
    main()
  File "/app/main.py", line 115, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 54, in listen_tydom
    await message_handler.incoming_triage()
  File "/app/tydom/MessageHandler.py", line 236, in incoming_triage
    await self.parse_response(incoming)
  File "/app/tydom/MessageHandler.py", line 298, in parse_response
    logger.warning('Unknown message type received', data)
Message: 'Unknown message type received'
Arguments: ('4231',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 119, in <module>
    main()
  File "/app/main.py", line 115, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 54, in listen_tydom
    await message_handler.incoming_triage()
  File "/app/tydom/MessageHandler.py", line 236, in incoming_triage
    await self.parse_response(incoming)
  File "/app/tydom/MessageHandler.py", line 298, in parse_response
    logger.warning('Unknown message type received', data)
Message: 'Unknown message type received'
Arguments: ('4231',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 119, in <module>
    main()
  File "/app/main.py", line 115, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 54, in listen_tydom
    await message_handler.incoming_triage()
  File "/app/tydom/MessageHandler.py", line 236, in incoming_triage
    await self.parse_response(incoming)
  File "/app/tydom/MessageHandler.py", line 298, in parse_response
    logger.warning('Unknown message type received', data)
Message: 'Unknown message type received'
Arguments: ('4230',)`

**Comment by Muspi** [comment]
Après un redémarrage, les infos ont été récupérées 1 fois, et depuis, plus rien :(

**Comment by Muspi** [comment]
@fmartinou pourrais tu m'indiquer comment installer une ancienne release stp?
Merci

**Comment by fmartinou** [comment]
Si tu déploies toi-même le conteneur, tu peux viser le tag docker de l'image que tu souhaites.

Si tu utilises le système d'addon home-assistant, il n'y a à  la connaissance pas possibilité de choisir sa version.
C'est peut-être possible en bidouillant des JSON ou des yaml quelque part mais je n'en sais rien ; je n'utilise pas les add-ons home-assistant personnellement.

**Comment by Muspi** [comment]
Oui, j'utilise l addon HA malheureusement....
Du coup je suis bien embêté.
Le comportent est très étrange. Les unfos sont récupérées seulement quand je redémarre HA  puis plus rien...

**Comment by fmartinou** [comment]
Tu as le problème que sur des tywatt?
C'est possible qu'il y ait eu une régression car j'ai fait un gros refacto la semaine dernière (refacto nécessaire car le code historique manque vraiment de qualité et la maintenabilité est devenue trop compliquée).

Il se peut que les tywatt fonctionnaient par polling et que le polling ne se fasse plus.
Je vais regarder dès que je peux mais je manque clairement de temps libre en ce moment 😔.


Dans le même temps, vérifie que tu utilises bien l'IP locale de la tydom et non pas la communication via internet car le système est beaucoup plus instable en passant par médiation.tydom.com.

**Comment by Muspi** [comment]
Oui  il me semble que dans un précédent ticket il y avait eu une histoire de polling qui spammait la tydom et la faisait planter, quand on activant le track9ng des consoles. Ça doit donc être bien un souci de polling car je n'ai effectivement le cas que sur les tywatt.

Piur l'IP c'est bien la locale que j'ai mis

**Comment by jrlacharnay** [comment]
Salut,

J'ai exactement le même problème avec mon Tydom+Calybox, seulement pour les entités de mesure de la consommation électrique. Je peux fournir des logs si ça peut aider.

En 3.0.0, çà fonctionne bien, la régression est sur la 3.0.1.

@Muspi, pour passer à la version 3.0.0, tu peux le faire via le système de Backup des addons (par défaut, un backup des addons est fait avant toute mise à jour).

**Comment by Muspi** [comment]
Ah, merci @jrlacharnay. Peux-tu m'indiquer comment je recharce ce backup
stp?
En te remerciant

Le lun. 3 avr. 2023 à 15:39, jrlacharnay ***@***.***> a
écrit :

**Comment by jrlacharnay** [comment]
Paramètres > Système > Sauvegardes. Cliques sur la sauvegarde appelée "addon_XXXX_tydom2mqtt_3.0.0", coche les cases et cliques sur RESTORE.

Puis redémarres HA (ça n'est normalement pas nécessaire, mais pour ce problème en particulier, ça semble l'être).

**Comment by Muspi** [comment]
Eh bien écoute, je viens de repasser en 2.6.6, et malheureusement ça a
l'air de ne plus fonctionner correctement :(

**Comment by faber357** [comment]
Même problème chez moi. Je suis revenu en 2.6.6 en attendant un fix

**Comment by alain-metzger** [comment]
Bonjour,
J'ai le même problème que cité précédemment avec un tydom + calybox.
J'ai installé HA au mois de mars 2023. Ma version actuelle de tydom2mqtt est 3.0.2
Je ne peux malheureusement pas faire de restauration sur la version 2.6.6 qui semblerait fonctionner d'après les messages que je lis (le 1er backup dont je dispose est la version 3.0.1)
Y a t-il un autre moyen de revenir à la version 2.6.6 ?

**Comment by robinoux** [comment]
BOnjour, avez vous trouver une solution ? j'ai le meme problème... Merci

**Comment by Bobdugrand8** [comment]
Bonjour,
Pour l'instant la seule solution est d'utiliser la version 2.6.6.
Il y a une PR proposée pour corriger le problème, mais pour l'instant elle n'a pas été validée par le responsable du projet.

**Comment by robinoux** [comment]
Oui j'ai vu, mais étant nouveau sur HOme assistant, je ne dispose pas de cette version, sait tu comment l'avoir et l'installer? Merci

**Comment by Bobdugrand8** [comment]
Si vous n'avez pas de sauvegarde en 2.6.6, la solution c'est de créer un local add-on, mais la nouvelle version ne devrait pas tarder puisque la PR a été validée, donc je pense que le mieux c'est d'attendre un peu.

**Comment by fmartinou** [comment]
La PR contenant le polling vient d'être releasée (`3.4.3`).

**Comment by faber357** [comment]
Version 3.4.3 installée il y a quelques heures et les données remontent bien. Merci

**Comment by robinoux** [comment]
j'ai testé depuis hier, avec un polling par defaut de 300, cela fonctionne 2/3 heures et apres plus rien....
