### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by dbar333** [fmartinou/tydom2mqtt#95]
Hello,

I try to deploy tydom2mqq on Rapsbian PI3 and i have some problem
can you help me ?

root@raspi:/opt/tydom2mqtt # docker compose up
[+] Running 1/1
 ✔ Container tydom2mqtt  Recreated                                                                                               0.2s
Attaching to tydom2mqtt
tydom2mqtt  | Traceback (most recent call last):
tydom2mqtt  |   File "/app/main.py", line 2, in <module>
tydom2mqtt  |     import asyncio
tydom2mqtt  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
tydom2mqtt  |     from .base_events import *
tydom2mqtt  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
tydom2mqtt  |     import concurrent.futures
tydom2mqtt  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
tydom2mqtt  |     from concurrent.futures._base import (FIRST_COMPLETED,
tydom2mqtt  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
tydom2mqtt  |     import logging
tydom2mqtt  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
tydom2mqtt  |     _startTime = time.time()
tydom2mqtt  |                  ^^^^^^^^^^^
tydom2mqtt  | PermissionError: [Errno 1] Operation not permitted
tydom2mqtt exited with code 1
root@raspi:/opt/tydom2mqtt # 

docker-compose.yml 

version: '3'

services:
  tydom2mqtt:
    image: fmartinou/tydom2mqtt
    container_name: tydom2mqtt
    environment:
        - TYDOM_MAC=001A25xxxxxx
        - TYDOM_PASSWORD=MyPassWord
        - TYDOM_IP=192.168.xxx.xxx
        - LOG_LEVEL=DEBUG

i use Docker version 24.0.0-beta.2, build 67c4570   and Raspbian GNU/Linux 10 (buster)

Sorry for my very bas english

**Comment by frnicolas** [comment]
As-tu bien python3 d’installer? Et les modules nécessaires ?
Essaye de faire un docker exécutif -italien tydom2mqtt /bin/sh puis une fois dans ton container lancer la commande pupitre list. 
tu devrais avoir la même liste que dans le fichier /app/requirements.txt
